### ISSUE TITLE
Release checklist for 0.4.1

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#101]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mperrin](https://github.com/mperrin)**
_Tuesday Feb 09, 2016 at 00:08 GMT_
_Originally opened as https://github.com/mperrin/webbpsf/issues/101_

----

I'm going to be lazy and put both poppy and webbpsf stuff here. 

For poppy 0.4.1:
- [x] the two remaining docs issues
- [x] the FFTW wisdom issue
- [x] update version number
- [x] update release notes in docs
- [x] double check test suite on Travis
- [x] make sdist; test; upload to PYPI; upload docs.
- [x] once complete & happy, git tag release. 

For webbpsf 0.4.1:
- [x] have someone double check and confirm agreement with Marshall's fixes for #85, #90 
- [x] add unit test for #88 
- [x] update version number
- [x] update release notes in docs
- [x] re-run all notebooks and check in the results (for consistent orientations after SI rotation flips)
- [x] double check test suite on Travis
- [x] make sdist; test; upload to PYPI; upload docs.
- [x] once complete & happy, git tag release.
