### ISSUE TITLE
New Release Checklist

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#313]
Bunch of stuff we should do before the next releasse. 

- [ ] Merge PR #309 for WFIRST
- [ ] Merge PR #283 for NIRCam field dep
- [ ] Merge PR #294 for PSF grid on WFIRST (after 309)
- [ ] Release notes
- [ ] Prepare updated data files source on Central Store
  - [ ] Update WFIRST data files (@robelgeda)
  - [ ] Update JWST SIs filter throughputs from Pandeia, except FGS  (@mperrin)
  - [x] Update JWST FGS throughput (#276; @shanosborne)
  - [x] Add NIRCam WLP4 as a filter (#306; @mperrin)

- [ ] Re-release data files
- [ ] Check other items on the milestone 0.8.1 issues list (@mperrin)
- [ ] Decide if this should be 0.9.0 instead of 0.8.1. Probably yes?

**Comment by mperrin** [comment]
FYI @shanosborne @robelgeda @Skyhawk172 @obi-wan76  - here's my working list of things we should keep in mind while trying to polish off a webbpsf release in the next few days (or get as close as possible, anyway).
