### ISSUE TITLE
Refresh documentation

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#4]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mperrin](https://github.com/mperrin)**
_Monday Jun 25, 2012 at 05:57 GMT_
_Originally opened as https://github.com/mperrin/webbpsf/issues/4_

----

# Documentation issues checklist
- [x] Remove commented text from `webbpsf.rst` (and elsewhere)
- [x] Mention `:py:attr:JWInstrument.options` where appropriate in `webbpsf.rst` #24 
- [x] Update instrument subclassing example (refers to `webbpsf.TFI`, `ThinLens` without `radius`)
- [x] Move `poppy.rst` into POPPY (if there's information there that isn't already in the POPPY docs). Should leave just enough discussion in webbpsf docs to explain at a high level what POPPY is and how it is used in WebbPSF, just so that WebbPSF users can have some technical sense of how it works under the hood without having to jump to the full POPPY documentation. 
- [x] Change the module index to link directly to the `webbpsf` module page
- [x] Remove all mention of Python 2.6.x support #27 
- [x] Explain (or explain in POPPY docs and link to) how to set `use_multiprocessing` #23 
- [x] Set up [intersphinx](http://sphinx-doc.org/ext/intersphinx.html) for references to POPPY
- [x] Link to `poppy.Instrument` `options` attribute docs from JWInstrument (depends on intersphinx?)
- [x] Add documentation for image jitter options to WebbPSF docs. 
- [x] Add documentation for package level configuration settings
- [x] ttk interface screenshots look worse than the ttk interface actually does these days... time to update them
- [x] Figure out why some :py:meth:'foo' style links (with backticks) won't resolve
- [x] anything to improve for logging functionality docs?
- [x] how to output intermediate step images

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Monday Jun 25, 2012 at 06:00 GMT_

----

document output mode that _only_ saves the downsampled image, etc.

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Friday Sep 13, 2013 at 19:03 GMT_

----

Need to document new configuration settings system.

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Wednesday Sep 03, 2014 at 20:46 GMT_

----

Much progress in recent commits.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Monday Nov 24, 2014 at 23:04 GMT_

----

@mperrin: Which of the things you mentioned above are still outstanding, if any? Feel free to edit this checklist. 

_Moved checklist to initial comment so the progress bar will show up on the issues list page._

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Tuesday Nov 25, 2014 at 00:18 GMT_

----

Some updates added. Thanks for organizing this.

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Wednesday Jan 21, 2015 at 01:54 GMT_

----

Closed via pull request https://github.com/mperrin/webbpsf/pull/33

Thanks for all your efforts cleaning up all these details and generally polishing the presentation - much appreciated.
