### ISSUE TITLE
Roadmap: OPD Analysis tools for flight and commissioning

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#448]
For use during flight commissioning and checkout, we will want to be able to do the following:

- [x] Load an OPD produced by the WAS into WebbPSF and generate PSFs for NIRCam, and compare back to the observed PSFs (optionally, backing out the NIRCam SI internal WFE from the input OPD)
- [ ] Update WebbPSF's model of OTE field dependence based on MIMF or CMIMF measurements; load an OPD measured for NIRCam FP1 and infer an OPD at any other SI field point. 
- [ ] Take a measured OPD and infer its spatial frequency content in the low/mid/high WFE bins, following e.g. the ISIM CV report Appendix E method (see JWST-RPT-032131)
- [x] Compare measured OPD properties to the optical budget (Lightsey et al.)
- [ ] Use WebbPSF to generate an ePSF grid for given instrument and filter; compare to a measured ePSF grid created with photutils (e.g. OTE-28 data). It's the code to compare two different ePSF grids that's the new feature here.

Each of the above is probably a separate issue and pull request.  I have code for some of this already started.

**Comment by mperrin** [comment]
FYI @shanosborne, @obi-wan76, @Skyhawk172, @grbrady - let me know if you can think of other things we might want to use webbpsf for in flight which would require additional code development before then.

**Comment by mperrin** [comment]
The above tasks were largely done, or equivalent better things done instead. In any case the telescope was successfully commissioned a couple years ago :-) So this issue can be closed.
