### ISSUE TITLE
Roadmap: In Flight Performance Updates

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#569]
- [x] LOS jitter to 1 mas. Done in  https://github.com/spacetelescope/webbpsf/pull/559
- [x] Add ability to use measured OPDs. Also in https://github.com/spacetelescope/webbpsf/pull/559
- [x] Add new OPD representing typical/average in flight alignment in early cycle 1
  - [x] Update data files distributions
  - [x] Make that new OPD the default OPD
- [ ] Update pupil model for measured obscurations on SMSS struts
- [ ] Update MIRI coronagraph pupil shear
- [ ] Update MIRI cruciform model
- [ ] Update/refactor SI pupil distortion models 
- [ ] Update documentation
