### ISSUE TITLE
Next Release Checklist

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#577]
- [x] Update default OPD @mperrin. (Done in #584)
- [x] Recommend to @ariedel a particular OPD for use in ETC   - @obi-wan76 
- [x] Unit test for coron shift @mperrin 
- [x] Update docs for some of the options such as coron shift and source offset and detector position @obi-wan76 
- [ ] Update docs re throughput and what's counted in WebbPSF versus elsewhere such as the ETC engine OTE throughput file, since  this is a recurring point of confusion @mperrin [edit: Not happening for this release. This docs enhancement is not urgent and can be punted until later]
- [x] Make new data files zip @mperrin 
- [x] Remove MAST login stuff from the download code, since not needed any more with latest DMS @obi-wan76 
- [x] Update the using OPDs in flight docs page to also explain about the `load_wss_opd` function if you have a specific filename already. @obi-wan76 or @mperrin 
- [x] Merge all the dependabot PRs @ojustino 
- [x] Any issues or help desk tickets which are sufficiently urgent to require attention right now? (I don't know of any. -MP)

**Comment by mperrin** [comment]
@obi-wan76 Marcio I think at one point you had offered to add some text in the docs about the coronagraph shift option and source offsets, and how all that works, etc. Is that something you might be able to do, perhaps quickly on Monday? We shouldn't hold up the release for that; that's a minor thing and can be done later if it doesn't fit now. 

Similarly I'm going to punt adding more documentation about throughputs now; just do not have the time.

**Comment by marcio-melendez** [comment]
@mperrin yes, I'll try my best to do it on Monday morning.  I agree the release should not wait for this.

**Comment by marcio-melendez** [comment]
Re: Help desk tickets. No extra attention, the release itself will clarify some of the help desk inquiries.
