### ISSUE TITLE
Roadmap: In flight performance updates part 2

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#614]
Continues from #569 

- [ ] Update pupil model for measured obscurations on SMSS struts
- [ ]   Update MIRI coronagraph pupil shear
- [ ]   Update MIRI cruciform model
- [ ]   Update/refactor SI pupil distortion models
- [ ]   Update documentation
