### ISSUE TITLE
Release checklist for 0.4

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#80]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mperrin](https://github.com/mperrin)**
_Thursday Nov 19, 2015 at 23:02 GMT_
_Originally opened as https://github.com/mperrin/webbpsf/issues/80_

----

- [x] Add WFIRST page to Sphinx docs @josePhoenix 
- [x] Review WFIRST notebook one last time @mperrin
- [x] Update (some) figures in Sphinx docs for better color tables consistency etc. 
- [x] Regenerate updated filter tables for NIRISS see #66 and #78 
- [x] Update docs for #77 
- [x] Regenerate data files, version number marked as 0.4.0
- [x] bump webbpsf version number in setup.py
- [x] consider bumping DATA_VERSION_MIN in `__init__`, but probably don't. The WFIRST stuff will depend on having that version, but JWST-focused users could keep running with the old data just fine in most cases.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Thursday Nov 19, 2015 at 23:32 GMT_

----

I'm not sure, but I think this might be the first public version that even tests `DATA_VERSION_MIN`?

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Thursday Nov 19, 2015 at 23:49 GMT_

----

oh good point. So we might as well push it all the way to 0.4. 

Also
- [x] write a 'what's new in 0.4' section of the docs.

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Friday Nov 20, 2015 at 06:36 GMT_

----

Basically all ready to go, pending any last minute notebook tweaks and possibly #84

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Friday Nov 20, 2015 at 12:34 GMT_

----

Looks like the new data file isn't happy on Travis. It's the new NIRISS filter curves which are timing out in the non-pysynphot code path. I remember something like this from making the MIRI updates and I'm sure it's going to be the same fix. 
- [x] Fix new NIRISS filter files so the interpolation step doesn't time out

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Friday Nov 20, 2015 at 14:33 GMT_

----

- [x] Update NIRCam coronagraph calls to use a version of that code in `webbpsf.optics` instead of the deprecated one in `poppy`

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Friday Nov 20, 2015 at 17:00 GMT_

----

- [x] NIRISS filters fixed and tests, just need to recreate the zip files when I get back to my desktop.
