### ISSUE TITLE
Release 1.3 roadmap

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#808]
See also [GitHub issues for release 1.3](https://github.com/spacetelescope/webbpsf/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+1.3%22) and [PRs for release 1.3](https://github.com/spacetelescope/webbpsf/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Release+1.3%22).

**PRs to complete and merge for this release:**
- [x] #768 @obi-wan76 
- [x] #787 @mperrin 
- [x] #770 @mperrin
- [ ] #675 @mperrin

**Tasks to do before release:**
- [ ] NIRISS GR700XD model improvements. (not yet a PR) @obi-wan76 
- [ ]  add some smaller issues regarding improvements in a couple of function @obi-wan76 
- [ ] Documentation about PSF subtraction examples @obi-wan76 
- [ ] Notebook example on how to create very large PSFs @obi-wan76 
- [x] Data files update, needed for #770 and probably also the GR700XD

**Comment by mperrin** [comment]
Marking this closed since 1.3.0 already happened.
