### ISSUE TITLE
Release 1.4 roadmap

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#863]
The following items were on the Release 1.3 roadmap (#808) but were deferred beyond that release: 

- [ ]  NIRISS GR700XD model improvements. (not yet a PR) @obi-wan76
- [ ] add some smaller issues regarding improvements in a couple of function @obi-wan76 
- [ ] Documentation about PSF subtraction examples @obi-wan76 
- [ ] Notebook example on how to create very large PSFs @obi-wan76

Draft PRs intentionally delayed to after 1.3: 

- [ ] #675 
- [ ] #838

**Comment by obi-wan76** [comment]
Notebook about PSF subtraction already released in 1.3
